# Generated by Django 4.0.6 on 2022-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0002_crimes2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes2001',
            name='Community_area',
            field=models.FloatField(null=True),
        ),
    ]
